name: AC295
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cloudpickle=1.4.1
  - cryptography=2.9.2
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.15.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.64.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.9
  - imageio=2.8.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.1
  - ipympl=0.5.6
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9c
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=2.1.2
  - jupyterlab_server=1.1.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.34.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.9
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - networkx=2.4
  - nodejs=10.13.0
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.4
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.1
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.23.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - albumentations==0.4.5
    - astunparse==1.6.3
    - augmentor==0.2.8
    - cachetools==4.1.0
    - colorama==0.4.3
    - dill==0.3.1.1
    - efficientnet==1.0.0
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.5
    - gitpython==3.1.2
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.51.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - image-classifiers==1.0.0
    - imgaug==0.2.6
    - jupyterlab-git==0.20.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.1
    - markdown==3.2.2
    - nbdime==2.0.0
    - oauthlib==3.1.0
    - opencv-python-headless==4.2.0.34
    - opt-einsum==3.2.1
    - promise==2.3
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.1
    - python-graphviz==0.14
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - segmentation-models==1.0.1
    - sidecar==0.4.0
    - smmap==3.0.4
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - tensorflow-examples==63ee35adcc3e3dd2d228bc3283e27f6a1e2158ab-
    - tensorflow-metadata==0.15.2
    - termcolor==1.1.0
    - tfds-nightly==3.1.0.dev202005120106
    - tqdm==4.46.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /home/ian/anaconda3/envs/AC295

